### ISSUE TITLE
NameError - uninitialized constant Jinda::User: in Rails 5.2.1

### ISSUE THREAD

**Issue by kul1** [kul1/jinda#5]
NameError - uninitialized constant Jinda::User:
  app/controllers/jinda_controller.rb:436:in `create_xmain'
  app/controllers/jinda_controller.rb:46:in `init'

**Comment by kul1** [comment]
It work fine in Rails 5.2.0

**Comment by kul1** [comment]
Moved user model to Jinda::User and all called
